/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cadastro.escolar;
import DAO.UsuarioDAO;
import Dados.SeusDados;
import javax.swing.JOptionPane;


public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
      // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
      private void initComponents() {

            jLabel5 = new javax.swing.JLabel();
            jTextField1 = new javax.swing.JTextField();
            jLabel2 = new javax.swing.JLabel();
            jLabel3 = new javax.swing.JLabel();
            jLabel4 = new javax.swing.JLabel();
            jButton1 = new javax.swing.JButton();
            jButton2 = new javax.swing.JButton();
            jPasswordField1 = new javax.swing.JPasswordField();
            jLabel1 = new javax.swing.JLabel();

            jLabel5.setBackground(new java.awt.Color(0, 0, 0));
            jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 255), 2));
            jLabel5.setOpaque(true);

            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
            setPreferredSize(new java.awt.Dimension(800, 800));
            getContentPane().setLayout(null);

            jTextField1.setFont(new java.awt.Font("Candara Light", 1, 18)); // NOI18N
            jTextField1.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jTextField1ActionPerformed(evt);
                  }
            });
            getContentPane().add(jTextField1);
            jTextField1.setBounds(500, 180, 230, 30);

            jLabel2.setBackground(new java.awt.Color(0, 0, 0));
            jLabel2.setFont(new java.awt.Font("Britannic Bold", 1, 36)); // NOI18N
            jLabel2.setText("Seu Cadastro");
            getContentPane().add(jLabel2);
            jLabel2.setBounds(500, 80, 330, 30);

            jLabel3.setBackground(new java.awt.Color(0, 0, 0));
            jLabel3.setFont(new java.awt.Font("Yu Gothic UI", 1, 22)); // NOI18N
            jLabel3.setText("Email");
            getContentPane().add(jLabel3);
            jLabel3.setBounds(500, 140, 190, 40);

            jLabel4.setBackground(new java.awt.Color(0, 0, 0));
            jLabel4.setFont(new java.awt.Font("Yu Gothic UI", 1, 22)); // NOI18N
            jLabel4.setText("Senha");
            getContentPane().add(jLabel4);
            jLabel4.setBounds(500, 210, 160, 30);

            jButton1.setBackground(new java.awt.Color(0, 0, 0));
            jButton1.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
            jButton1.setForeground(new java.awt.Color(255, 255, 255));
            jButton1.setText("Login");
            jButton1.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jButton1ActionPerformed(evt);
                  }
            });
            getContentPane().add(jButton1);
            jButton1.setBounds(510, 377, 200, 40);

            jButton2.setBackground(new java.awt.Color(0, 0, 0));
            jButton2.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
            jButton2.setForeground(new java.awt.Color(255, 255, 255));
            jButton2.setText("Cadastro");
            getContentPane().add(jButton2);
            jButton2.setBounds(510, 305, 200, 40);
            jButton2.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jButton2ActionPerformed(evt);
                  }
            });

            jPasswordField1.setFont(new java.awt.Font("Candara Light", 1, 18)); // NOI18N
            jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jPasswordField1ActionPerformed(evt);
                  }
            });
            getContentPane().add(jPasswordField1);
            jPasswordField1.setBounds(500, 250, 230, 30);

            jLabel1.setBackground(new java.awt.Color(255, 255, 255));
            jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 2, 18)); // NOI18N
            jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cadastro/escolar/banner-cadastro-de-clientes.png"))); // NOI18N
            jLabel1.setOpaque(true);
            getContentPane().add(jLabel1);
            jLabel1.setBounds(-180, -20, 1130, 620);

            setSize(new java.awt.Dimension(816, 533));
            setLocationRelativeTo(null);
      }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

      private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            UsuarioDAO checar = new UsuarioDAO();
            System.out.println("aqui  rodoou");
            if(checar.checkLogin(jTextField1.getText(), jPasswordField1.getText())){
                  
             System.out.println("aqui tbm");
             SeusDados a1 =new SeusDados();
             System.out.println("aqui  rodoou  tbm");
             a1.Valores(jTextField1.getText());
             System.out.println("aqui  tbm roddou");
             a1.setVisible(true);
             this.dispose();
            }
            else{
            JOptionPane.showMessageDialog(null, "Errado");
            }
      }//GEN-LAST:event_jButton1ActionPerformed

      private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
            // TODO add your handling code here:
      }//GEN-LAST:event_jPasswordField1ActionPerformed
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        Cadastrar a1 = new Cadastrar();
        a1.setVisible(true);
        setVisible(false);
    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

      // Variables declaration - do not modify//GEN-BEGIN:variables
      private javax.swing.JButton jButton1;
      private javax.swing.JButton jButton2;
      private javax.swing.JLabel jLabel1;
      private javax.swing.JLabel jLabel2;
      private javax.swing.JLabel jLabel3;
      private javax.swing.JLabel jLabel4;
      private javax.swing.JLabel jLabel5;
      private javax.swing.JPasswordField jPasswordField1;
      private javax.swing.JTextField jTextField1;
      // End of variables declaration//GEN-END:variables
}
