/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Dados;

import DAO.ConnectionFactory;
import DAO.UsuarioDAOCD;
import Model.Usuario;
import cadastro.escolar.Login;
import java.sql.Connection;
import javax.swing.JOptionPane;



/**
 *
 * @author bibop
 */
public class SeusDados extends javax.swing.JFrame {

      
      
      public SeusDados() {
            
            initComponents();
           
      }

      /**
       * This method is called from within the constructor to initialize the
       * form. WARNING: Do NOT modify this code. The content of this method is
       * always regenerated by the Form Editor.
       */
      @SuppressWarnings("unchecked")
      // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
      private void initComponents() {

            imagem = new javax.swing.JLabel();
            jLabel2 = new javax.swing.JLabel();
            jLabel3 = new javax.swing.JLabel();
            rm = new javax.swing.JLabel();
            jLabel6 = new javax.swing.JLabel();
            Idade = new javax.swing.JLabel();
            jLabel8 = new javax.swing.JLabel();
            email = new javax.swing.JLabel();
            jLabel10 = new javax.swing.JLabel();
            jLabel11 = new javax.swing.JLabel();
            jButton1 = new javax.swing.JButton();
            nome = new javax.swing.JLabel();

            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
            setBackground(new java.awt.Color(255, 255, 255));
            setMinimumSize(new java.awt.Dimension(1200, 800));
            getContentPane().setLayout(null);
            getContentPane().add(imagem);
            imagem.setBounds(520, 130, 160, 167);

            jLabel2.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
            jLabel2.setText("Nome:");
            getContentPane().add(jLabel2);
            jLabel2.setBounds(390, 320, 100, 43);

            jLabel3.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
            jLabel3.setText("RM:");
            getContentPane().add(jLabel3);
            jLabel3.setBounds(390, 370, 60, 40);

            rm.setFont(new java.awt.Font("Courier New", 0, 36)); // NOI18N
            getContentPane().add(rm);
            rm.setBounds(450, 360, 240, 40);

            jLabel6.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
            jLabel6.setText("Idade:");
            getContentPane().add(jLabel6);
            jLabel6.setBounds(390, 410, 120, 40);

            Idade.setFont(new java.awt.Font("Courier New", 0, 36)); // NOI18N
            getContentPane().add(Idade);
            Idade.setBounds(510, 410, 190, 40);

            jLabel8.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
            jLabel8.setText("Email:");
            getContentPane().add(jLabel8);
            jLabel8.setBounds(390, 460, 120, 40);

            email.setFont(new java.awt.Font("Courier New", 0, 36)); // NOI18N
            getContentPane().add(email);
            email.setBounds(510, 450, 440, 50);

            jLabel10.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
            jLabel10.setText("Serie:");
            getContentPane().add(jLabel10);
            jLabel10.setBounds(390, 510, 120, 40);

            jLabel11.setFont(new java.awt.Font("Courier New", 0, 36)); // NOI18N
            getContentPane().add(jLabel11);
            jLabel11.setBounds(510, 510, 110, 30);

            jButton1.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
            jButton1.setText("Voltar");
            jButton1.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jButton1ActionPerformed(evt);
                  }
            });
            getContentPane().add(jButton1);
            jButton1.setBounds(540, 600, 110, 40);

            nome.setFont(new java.awt.Font("Courier New", 0, 36)); // NOI18N
            getContentPane().add(nome);
            nome.setBounds(490, 320, 410, 40);

            setSize(new java.awt.Dimension(1216, 808));
            setLocationRelativeTo(null);
      }// </editor-fold>//GEN-END:initComponents

      private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            Login a1 = new Login();
            a1.setVisible(true);
            setVisible(false);
      }//GEN-LAST:event_jButton1ActionPerformed

      public void  Valores(String entrada){
            ConnectionFactory  a1 =  new  ConnectionFactory();
            UsuarioDAOCD Consulta = new UsuarioDAOCD();
            Usuario Dados = Consulta.Consultar(entrada);
            boolean  status  = a1.conectar();
            if(status==true){
            
            
            
           
            System.out.println( Dados.getIdade());
            nome.setText(Dados.getNome());
            rm.setText(Dados.getRM());
            Idade.setText(Dados.getIdade());
            email.setText(Dados.getEmail());
            
            
            }
            else{
            JOptionPane.showMessageDialog(null, "não conectou");
            
            }
            String sexo  = Dados.getSexo();
            if("Femn".equals(sexo)){
            imagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/menina (Personalizado).jpg")));
            System.out.println( "ò foio");
            }
            if("Masc".equals(sexo)){
            imagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/menino (Personalizado).jpg")));
            System.out.println( "ò foio");
            }
           
      
      }
      
      // Variables declaration - do not modify//GEN-BEGIN:variables
      private javax.swing.JLabel Idade;
      private javax.swing.JLabel email;
      private javax.swing.JLabel imagem;
      private javax.swing.JButton jButton1;
      private javax.swing.JLabel jLabel10;
      private javax.swing.JLabel jLabel11;
      private javax.swing.JLabel jLabel2;
      private javax.swing.JLabel jLabel3;
      private javax.swing.JLabel jLabel6;
      private javax.swing.JLabel jLabel8;
      private javax.swing.JLabel nome;
      private javax.swing.JLabel rm;
      // End of variables declaration//GEN-END:variables
}
